server {
    listen 80;

    # Nginx sert les fichiers depuis public/ de Symfony
    root  /var/www/html/public;
    index index.php;

    location / {
        # Cherche un fichier statique correspondant à l'URL.
        # Si rien trouvé → passe à index.php (le routeur de Symfony).
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        # Transmet la requête à PHP-FPM
        # "php" = nom du conteneur Docker (résolu automatiquement en IP)
        # 9000  = port standard de PHP-FPM
        fastcgi_pass php:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT   $realpath_root;
    }

    # Bloquer l'accès aux fichiers cachés (.env, .git...)
    location ~ /\. {
        deny all;
    }
}
