parameters:

services:
    _defaults:
        autowire: true
        # autowire: true active l'injection de dépendances automatique.
        # Symfony lit les types des paramètres de constructeur
        # et injecte automatiquement les bons objets.

        autoconfigure: true
        # Symfony détecte le rôle de chaque classe automatiquement.
        # Exemple : une classe avec #[AsMessageHandler] sera
        # automatiquement enregistrée comme handler de messages.

        public: false
        # Les services sont privés : on ne peut les utiliser
        # qu'en les injectant via les constructeurs.
        # Cela force une architecture propre.

    App\:
        resource: '../src/'
        # Symfony scanne tout le dossier src/ et enregistre
        # chaque classe PHP comme un service potentiel.
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/DTO/'
            # Ces classes sont exclues car ce sont des objets de données,
            # pas des services à injecter.
